server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.174.128:1111 #配置Nacos地址
  profiles:
    active: dev # 表示开发环境
    #active: test # 表示测试环境
    #active: info
management:
  endpoints:
    web:
      exposure:
        include: '*'


