server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    #    alibaba:
    #      seata:
    #        registry:
    #          type: nacos
    #          nacos:
    #            application: seata-server
    #            server-addr: 127.0.0.1:8848
    #            group: "SEATA_GROUP"
    #            #namespace: ""
    #            username: "nacos"
    #            password: "nacos"
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata_order?rewriteBatchedStatements=true&characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

sfs:
  nacos:
    server-addr: 127.0.0.1:8848
    #namespace: 967df0d8-156b-441a-a5ab-615b4a865168
    group: SEATA_GROUP
seata:
  enabled: true
  application-id : ${spring.application.name}
  tx-service-group: default_tx_group
  use-jdk-proxy: true
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      server-addr: ${sfs.nacos.server-addr}
      #namespace: ${sfs.nacos.namespace}
      group: ${sfs.nacos.group}
      data-id: seataServer.properties
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: ${sfs.nacos.server-addr}
      #namespace: ${sfs.nacos.namespace}
      group: ${sfs.nacos.group}
  service:
    vgroupMapping:
      default_tx_group: default

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml